server {
    server_name routing.dnxroute.com;
    root /var/www/routing;
    index index.html;

    location /rt/node1/ {
        proxy_pass http://127.0.0.1:4600/;
    }
    location /rt/node2/ {
        proxy_pass http://134.122.7.99:4600/;
    }
    location / { try_files $uri $uri/ =404; }

    listen [::]:443 ssl; # managed by Certbot
    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/routing.dnxroute.com/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/routing.dnxroute.com/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot

}
server {
    if ($host = routing.dnxroute.com) {
        return 301 https://$host$request_uri;
    } # managed by Certbot


    listen 80;
    listen [::]:80;
    server_name routing.dnxroute.com;
    return 404; # managed by Certbot


}